name: CraftBook
main: org.enginehub.craftbook.bukkit.CraftBookPlugin
version: "${internalVersion}"
dev-url: http://dev.bukkit.org/server-mods/craftbook/
softdepend: [WorldEdit, WorldGuard, ProtocolLib, Vault]
api-version: 1.13
commands:
