# CraftBook Configuration for Bukkit.
# This configuration will automatically add new configuration options for you,
# So there is no need to regenerate this configuration unless you want to.
# More information about these features are available at:
# https://craftbook.enginehub.org/en/latest/mechanics/
#
# NOTE! NOTHING IS ENABLED BY DEFAULT! ENABLE FEATURES TO USE THEM!


# List of mechanics and whether they are enabled or not
mechanics:
    circuit:
        jack_o_lantern: false
        jukebox: false
        redstone_fire: false
    general:
        better_plants: false
        marquee: false
        snow: false
        variables: true
    tool:
        ammeter: false
        lightstone: false

# WARNING! Changing this can result in all ST mechanics acting very weirdly, only change this if you know what you are doing!
st-think-ticks: 2

# Causes many mechanics to require sufficient blocks to function, for example gates, bridges and doors.
safe-destruction: true

# If on, OP's will not default to have access to everything.
no-op-permissions: false

# Allows redstone not directly facing a mechanism to trigger said mechanism.
indirect-redstone: false

# Rounds all distance equations to the block grid.
use-block-distance: false

# Checks to see if WorldGuard allows building/using in the area when activating mechanics.
check-worldguard-flags: true

# Use advanced methods to detect if a player can build or not. Use this if you use region protections other than WorldGuard, or experience issues with WorldGuard protection. This can add extra entries to Block Logging plugins when a mechanic is broken/placed.
advanced-block-checks: true

# How often in milliseconds players can interact with CraftBook signs.
sign-click-timeout: 500

# Enable a mode that will print extra debug information to the console.
debug-mode: false

# Causes all debug mode output to be logged into a file. This file is reset every startup (And every /cb reload).
debug-mode-file-logging: false

# Enable certain debug types when debug mode is enabled.
debug-flags: []

# Show messages when a player does not have permission to do something.
show-permission-messages: true

# PersistentStorage stores data that can be accessed across server restart. Method of PersistentStorage storage (Note: DUMMY is practically off, and may cause issues). Can currently be any of the following: YAML, DUMMY, SQLite
persistent-storage-type: YAML
